### ISSUE TITLE
SkyScanResult tolerances

### ISSUE THREAD

**Issue by mlincett** [icecube/skyreader#8] opened 2023-05-23 07:44 UTC
From tests comparing a `MillipedeWilks` run on condor/grid vs CI it seems that reconstructed energy losses can differ up to 7% (so far) between the two.

LLH relative differences are still < 1E-4 so they pass the test.

I think we should allow reco losses differences up to 10%. @tianluyuan you think this is reasonable?

**Comment by tianluyuan** [comment] 2023-05-23 14:30
That's interesting.. I guess this is something that doesn't appear in `MillipedeOriginal` because those were generated on the CI worker. Though, if everything is run inside Singularity then shouldn't the results be reproducible to better than 10%? If there are differences in the llh between workers then we would also expect to see some of those fluctuations in the skymap.

In any case I think those tolerances are fine for now, maybe we can leave this open for reference.

**Comment by mlincett** [comment] 2023-05-23 14:39
I don't see such a big difference for the GOLD event, I will try to re-run the BRONZE to be sure I didn't mess up something.

**Comment by mlincett** [comment] 2023-05-23 22:42
From the "realistic" tests I see reco energies with differences as large as 16% and 1E-3 for LLH values.

For the moment I am adjusting the tolerances in the comparison script that runs in CI so to make all test pass. 

Once that is achieved, I could regenerate all the test data with the latest docker tag of the branch, so we have a baseline.

Note that there seem to be no environment variable that changes the setup between CI and condor for `millipede_wilks` (only for `millipede_original` we reduce the number of position variations in CI).

**Comment by ric-evans** [comment] 2023-06-06 21:06
not sure if we want to hard code these values, for the different configurations. Also, #9

**Comment by tianluyuan** [comment] 2024-10-04 03:35
I think this is related to icecube/skymap_scanner#200 and as that has been resolved we can close this.

**Closed** 2024-10-04 03:35 UTC
Labels: question
